version: 2
jobs:
  build:
    docker:
      - image: ericwooley/headless-chrome-node-docker
    steps:
      - checkout
      - run: docker run -v $PWD:/app/ -e NO_SANDBOX=true ericwooley/headless-chrome-node-docker /bin/bash -c "cd test; yarn; yarn test"